### ISSUE TITLE
Trivial Inaccuracy or Ambiguity in README.md

### ISSUE THREAD

**Issue by nicholasramsey** [jplatte/ShittyBinary#2]
> ...binary data in C++, because C++ only supports normal numbers natively

During the justification of this library's creation, it was implied that C++ does not natively support binary literals. That is not so. According to subsection 2.13.2 ([lex.icon]) of the latest standard draft (n4567) as well as various other reputable sources (namely, cppreference.com), binary literals have been ratified and should be available to all users of a C++14-compliant compiler.

**Comment by jplatte** [comment]
Dude, this is a parody. Apart from the horrible, horrible code, you did see the name, right?

**Comment by nicholasramsey** [comment]
I may have overlooked those details. Sorry for my ridiculous inattention.
